# Generated by Django 6.0.6 on 2026-06-14 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('has_schedule', models.BooleanField(default=False)),
                ('has_repertoire', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ministries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ministries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MinistryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ministries.ministry')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MinistryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Líder'), ('servant', 'Servo')], default='servant', max_length=20)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ministries.ministry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ministry', 'user')},
            },
        ),
        migrations.AddField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(related_name='ministries', through='ministries.MinistryMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField()),
                ('role', models.CharField(max_length=80)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_slots', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_slots', to='ministries.ministry')),
            ],
            options={
                'ordering': ['service_date'],
            },
        ),
    ]
